openapi: 3.0.0
info:
  title: Fastify API
  description: Fastify API with OpenAPI documentation
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /healthcheck:
    get:
      summary: Health Check
      description: Returns the health status of the API
      operationId: healthCheck
      tags:
        - Health
      responses:
        "200":
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error400"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error500"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error503"
  /heartbeat:
    get:
      summary: Heartbeat
      description: Returns the heartbeat status of the API
      operationId: heartbeat
      tags:
        - Health
      responses:
        "200":
          description: API heartbeat status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: alive
                  uptime:
                    type: number
                    description: Server uptime in seconds
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error400"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error500"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error503"
components:
  schemas:
    Error400:
      type: object
      properties:
        status:
          type: string
          example: "400"
        message:
          type: string
          example: "Bad Request"
    Error500:
      type: object
      properties:
        status:
          type: string
          example: "500"
        message:
          type: string
          example: "Internal Server Error"
    Error503:
      type: object
      properties:
        status:
          type: string
          example: "503"
        message:
          type: string
          example: "Service Unavailable"
