// This file is auto-generated from the .env file.
// Do not edit this file directly.
import { type Static, Type } from '@sinclair/typebox';

export const envSchema = Type.Object({
	PORT: Type.Number(),
	DATABASE_URL: Type.String(),
});

export type EnvType = Static<typeof envSchema>;
